Scale Factor: X2 	ZSSR: False 	Real Image: False
************************************************************
STARTED KernelGAN on: "/home/mo926312/Documents/kernelGAN/KernelGAN/training_data/input.mp4"...
Traceback (most recent call last):
  File "mytest.py", line 16, in <module>
    test(conf)
  File "mytest.py", line 9, in test
    data = DataGenerator(conf, gan)
  File "/home/mo926312/Documents/kernelGAN/KernelGAN/data.py", line 22, in __init__
    self.shave_edges(scale_factor=conf.scale_factor, real_image=conf.real_image) #FIX later for ZSSR
  File "/home/mo926312/Documents/kernelGAN/KernelGAN/data.py", line 81, in shave_edges
    self.input_image = self.input_image[10:-10, 10:-10, :]
AttributeError: 'DataGenerator' object has no attribute 'input_image'
